# site settings
title: My Personal Homepage 
subtitle: by Forty
email: mohamad.mehdi.jafari94@gmail.com
description:  Get ready to explore my digital playground, where <br />
              I showcase  my passions and adventures! While I strive  <br />
              to update it pronto, crafting content is no cakewalk ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meti-94.github.io" # the base hostname & protocol for your site
author:
street_address: St. Shahed, St. Motahari
city: Abadeh
state: Fars, 
zip_code: 
country: Iran
phone: (98) 921-980-5154

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/meti-94
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/mohammad-mehdi-jafari94/
  Twitter: https://twitter.com/mehdi02896710
  Facebook:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- vendor